name: 🧩 Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v7

      - name: 📦 Zip the integration
        run: |
          cd custom_components/material_home_assistant
          zip -r ../../material_home_assistant.zip .

      - name: 🚀 Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./material_home_assistant.zip